### ISSUE TITLE
Error with command 

### ISSUE THREAD

**Issue by PDevChris** [supercrafter333/AsyncWorldReset#2]
Hello when command is run by using /worldreset it gives you this error. 

[02:40:56.545] [Server thread/CRITICAL]: Error: "Call to undefined method supercrafter333\AsyncWorldReset\tasks\asynchronous\RemoveWorldTask::getInstance()" (EXCEPTION) in "plugins/AsyncWorldReset.phar/src/AsyncWorldReset" at line 107
--- Stack trace ---
  #0 (): supercrafter333\AsyncWorldReset\tasks\asynchronous\RemoveWorldTask->supercrafter333\AsyncWorldReset\{closure}()
  #1 plugins/AsyncWorldReset.phar/src/tasks/asynchronous/RemoveWorldTask(53): Closure->call(object supercrafter333\AsyncWorldReset\tasks\asynchronous\RemoveWorldTask#180389)
  #2 pmsrc/src/scheduler/AsyncPool(268): supercrafter333\AsyncWorldReset\tasks\asynchronous\RemoveWorldTask->onCompletion()
  #3 pmsrc/src/scheduler/AsyncPool(140): pocketmine\scheduler\AsyncPool->collectTasksFromWorker(int 1)
  #4 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(123): pocketmine\scheduler\AsyncPool->pocketmine\scheduler\{closure}()
  #5 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(82): pocketmine\snooze\SleeperHandler->processNotifications()
  #6 pmsrc/src/Server(1703): pocketmine\snooze\SleeperHandler->sleepUntil(float 1669689656.5468)
  #7 pmsrc/src/Server(1061): pocketmine\Server->tickProcessor()
  #8 pmsrc/src/PocketMine(328): pocketmine\Server->__construct(object BaseClassLoader#4, object pocketmine\utils\MainLogger#3, string[16] /home/container/, string[24] /home/container/plugins/)
  #9 pmsrc/src/PocketMine(351): pocketmine\server()
  #10 pmsrc(11): require(string[60] phar:///home/container/PocketMine-MP.phar/src/PocketMine.php)
--- End of exception information ---
[02:40:56.545] [Server thread/EMERGENCY]: An unrecoverable error has occurred and the server has crashed. Creating a crash dump

**Comment by supercrafter333** [comment]
Will be fixed soon.
